version: "3.8"

services:
  web:
    build: .
    image: rsp-system:0.0.3
    ports:
      - "8000:8000"
      - "8090:8090"
    env_file:
      - .env

  mongodb:
    image: mongo:4.2.19
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

# Persistent Data Volume
volumes:
  data:
